#include <iostream>

int main()
{
	// Values to create Fibonacci Sequence
	int val1 = 1, val2 = 2, nextVal = 0;

	// Problem Values - Constraint and Sum
	int maxVal = 4000000;
	int sum = 0;

	std::cout << "Project Euler: Problem 2 - Even Fibonacci Numbers.\n\n";

	std::cout << "Fibonacci Series: " << val1 << ", " << val2;

	while (val2 <= maxVal) 
	{
		nextVal = val1 + val2;
		val1 = val2;
		val2 = nextVal;
		std::cout << ", " << nextVal;

		if (val2 % 2 == 0) {
			sum += val2;
		}
	}

	std::cout << "\nSum of the Even Sequence: " << sum << "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
}

/*
* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be :
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
* By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.
* 
* 
* How to get values -> Add Previous Value with Current to make Next -> nv = v1+v2
* 
*/